FROM node:22-alpine

RUN corepack enable

WORKDIR /usr/src/app

COPY pnpm-lock.yaml ./
COPY pnpm-workspace.yaml ./
COPY package.json ./
COPY turbo.json ./

COPY ./packages ./packages
COPY ./apps/sketchsync ./apps/sketchsync

RUN pnpm install --frozen-lockfile

RUN pnpm --filter @repo/db build || true

ARG NEXT_PUBLIC_BACKEND_URL
ARG NEXT_PUBLIC_WS_URL

ENV NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL
ENV NEXT_PUBLIC_WS_URL=$NEXT_PUBLIC_WS_URL

RUN pnpm run db:generate

EXPOSE 3000

CMD ["pnpm", "run", "start:web"]